In [1]:
import pandas as pd
import numpy as np
import spacy
from textblob import TextBlob
from sklearn.metrics import classification_report

In [2]:
data = pd.read_csv('https://drive.google.com/uc?id=1_nbSPqf4a3x2gH38syU75gFh5JXojY6B',nrows=10000)
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
data['TextBlob_Subjectivity'] = data['review'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
data['TextBlob_Polarity'] = data['review'].apply(lambda x: TextBlob(x).sentiment.polarity)

In [4]:
data[['TextBlob_Subjectivity','TextBlob_Polarity']]

      TextBlob_Subjectivity  TextBlob_Polarity
0                  0.490369           0.023433
1                  0.559343           0.109722
2                  0.658730           0.354008
3                  0.454167          -0.057813
4                  0.452916           0.217952
...                     ...                ...
9995               0.509470           0.249811
9996               0.467606           0.066324
9997               0.564084           0.021673
9998               0.533131          -0.020000
9999               0.531250           0.120536

[10000 rows x 2 columns]

In [5]:
data['TextBlob_Analysis'] = data['TextBlob_Polarity'].apply(lambda x: 'negative' if x<0 else 'positive')

In [6]:
data

,review,sentiment,TextBlob_Subjectivity,TextBlob_Polarity,TextBlob_Analysis
0,One of the other reviewers has mentioned that ...,positive,0.490369,0.023433,positive
1,A wonderful little production. <br /><br />The...,positive,0.559343,0.109722,positive
2,I thought this was a wonderful way to spend ti...,positive,0.658730,0.354008,positive
3,Basically there's a family where a little boy ...,negative,0.454167,-0.057813,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,0.452916,0.217952,positive
...,...,...,...,...,...
9995,"Fun, entertaining movie about WWII German spy ...",positive,0.509470,0.249811,positive
9996,Give me a break. How can anyone say that this ...,negative,0.467606,0.066324,positive
9997,This movie is a bad movie. But after watching ...,negative,0.564084,0.021673,positive
9998,This is a movie that was probably made to ente...,negative,0.533131,-0.020000,negative
9999,Smashing film about film-making. Shows the int...,positive,0.531250,0.120536,positive

In [7]:
print(classification_report(data['sentiment'], data['TextBlob_Analysis']))

              precision    recall  f1-score   support

    negative       0.89      0.44      0.58      4972
    positive       0.63      0.94      0.75      5028

    accuracy                           0.69     10000
   macro avg       0.76      0.69      0.67     10000
weighted avg       0.76      0.69      0.67     10000